name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      tokenizers_proto_version:
        required: true

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
      # Start downloads
      - run: sudo apt install -y unzip
      - name: linux-arm64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/linux-arm64.zip"
          unzip "linux-arm64.zip" -d natives/linux-arm64
      - name: linux-x64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/linux-x64.zip"
          unzip "linux-x64.zip" -d natives/linux-x64
      - name: darwin-arm64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/darwin-arm64.zip"
          unzip "darwin-arm64.zip" -d natives/darwin-arm64
      - name: darwin-x64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/darwin-x64.zip"
          unzip "darwin-x64.zip" -d natives/darwin-x64
      - name: win32-arm64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/windows-arm64.zip"
          unzip "windows-arm64.zip" -d natives/win32-arm64
      - name: win32-x64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/windows-x64.zip"
          unzip "windows-x64.zip" -d natives/win32-x64
      # Finish downloads
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          cd natives
          npm publish --ws --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
