name: Release-Natives
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      tokenizers_proto_version:
        required: true

jobs:
  pack:
    runs-on: ubuntu-latest
    env:
      NATIVES: "linux-arm64 linux-x64 darwin-arm64 darwin-x64 win32-arm64 win32-x64"
      RUST_RUNTIMES: "aarch64-linux-gnu x86_64-linux-gnu aarch64-darwin x86_64-darwin aarch64-windows x86_64-windows"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}
      # Start downloads
      - name: download libraries
        run: |
          read -a natives <<< "${{ env.NATIVES }}"
          read -a rust_runtimes <<< "${{ env.RUST_RUNTIMES }}"
          for ((i=0;i<${#natives[@]};i++))
          do
            mkdir -p ./natives/${natives[i]}
            curl -L "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/${rust_runtimes[i]}.tar.gz" |
            tar -xzf - -C ./natives/${net_runtimes[i]}
          done
      # Finish downloads
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          cd natives
          npm publish --ws --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
