name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
env:
  PROTOC_VERSION: "32.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: v${{ inputs.version }}
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - name: install packages
        run: |
          sudo apt update
          sudo apt install unzip
      - name: install protoc
        run: |
          PROTOC_ZIP="protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip"
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/$PROTOC_ZIP"
          unzip $PROTOC_ZIP -d $HOME/.protoc
      - name: update path
        run: echo "$HOME/.protoc/bin" >> $GITHUB_PATH
      - name: build
        run: |
          mv deno.json deno-publish.json
          mv package.json package-bun.json
          mv package-build.json package.json
          deno install
          sudo chmod 755 protoc-gen-ts_proto.sh
          deno task generate
          mv package.json package-build.json
          mv deno-publish.json deno.json
      - name: publish
        run: deno publish --no-check --allow-dirty
